# https://github.com/berkshelf/berkshelf-api/issues/112
Encoding.default_external = "UTF-8"

source 'https://supermarket.chef.io'

cookbook 'consul',
	git: 'https://github.com/johnbellone/consul-cookbook.git',
	ref: '10d582a5450087a851a8c3168a0d7138150cedeb'

cookbook 'consul-client-config', path: 'consul-client-config/'
